### ISSUE TITLE
Error compiling shaders

### ISSUE THREAD

**Issue by am0ren0** [lecopivo/magnum-imgui#2]
Around line 416, where the NEW_GLSL defined is added to the default source code of the shaders, there is a NEWLINE missing and the shader compiler fails. Adding !\n" at the end fixes the problem

```
    vert.addSource({"#define NEW_GLSL\n"});
    frag.addSource({"#define NEW_GLSL\n"});

```
Cheers,
Alex

**Comment by lecopivo** [comment]
Thanks, fixed!
